print('==== DESAFIO 04 ====')
# USANDO MÉTODO 'IS'
algo = input('Digite qualquer coisa: ')
print('O tipo primitivo é', type(algo))
print('O conteúdo digitado pode ser Alfanúmerico? ', algo.isalnum())
print('O conteúdo digitado pode ser Alfabético? ', algo.isalpha())
print('O conteúdo digitado pode ser Númerico? ', algo.isnumeric())
print('O conteúdo digitado pode ser Printável? ', algo.isprintable())
print('O conteúdo digitado é apenas do alfabeto? ', algo.isascii())
print('O conteúdo digitado pode ser Decimal? ', algo.isdecimal())
print('O conteúdo digitado é Maiúsculo? ', algo.isupper())
print('O conteúdo digitado é Minúsculo? ', algo.islower())
print('O conteúdo digitado são Dígitos? ', algo.isdigit())
print('O conteúdo digitado é um Espaço? ', algo.isspace())
print('O conteúdo digitado é um Título? ', algo.istitle())
print('O conteúdo digitado pode ser um Identificador? ', algo.isidentifier())